# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Packages
      run: npm ci
      
    - name: Test
      run: npm run test
    
    - name: Deploy to GH Pages 🚀
      run: |
        echo ${{secrets.USER_NAME}}
        echo ${{secrets.EMAIL}}
        echo ${{secrets.PERSONAL_ACCESS_TOKEN}}
        git config --global user.name ${{secrets.USER_NAME}}
        git config --global user.email ${{secrets.EMAIL}}
        git remote set-url origin https://${{secrets.PERSONAL_ACCESS_TOKEN}}@github.com/${{secrets.USER_NAME}}/react-001.git
        npm run deploy
